# FunkGui's own binary-data embedder (v0.12.0), for a build without JUCE (FUNKGUI_WITH_JUCE=OFF), where there is no
# juce_add_binary_data. A script, run at build time by the FunkGuiFonts target of cmake/FunkGuiTargets.cmake:
#
#   cmake -DFUNKGUI_EMBED_OUT=<dir> -DFUNKGUI_EMBED_NAME=<stem> -DFUNKGUI_EMBED_NAMESPACE=<namespace>
#         "-DFUNKGUI_EMBED_FILES=<symbol>=<file>|<symbol>=<file>|..." -P cmake/FunkGuiEmbed.cmake
#
# It writes <dir>/<stem>.h and <dir>/<stem>.cpp, shaped like JUCE's BinaryData so that the same code reads either
# (include/funkgui/text/BundledFont.h names funkguifonts::JetBrainsMonoRegularsubset_ttf and its Size):
#
#   namespace <namespace>
#   {
#       extern const char* <symbol>;
#       const int          <symbol>Size = <bytes>;
#   }
#
# The bytes are an unsigned char array, 16 to a line; nothing is appended (no terminating NUL is counted). Plain CMake
# (file(READ … HEX)), so the build needs no other tool: a fraction of a second for the 0.5 MiB atlas.
cmake_minimum_required(VERSION 3.30)

foreach(_v FUNKGUI_EMBED_OUT FUNKGUI_EMBED_NAME FUNKGUI_EMBED_NAMESPACE FUNKGUI_EMBED_FILES)
  if("${${_v}}" STREQUAL "")
    message(FATAL_ERROR "FunkGuiEmbed.cmake: -D${_v}=… is required")
  endif()
endforeach()

string(REPLACE "|" ";" _files "${FUNKGUI_EMBED_FILES}")
# One string each, built with string(APPEND): the texts hold semicolons, which a CMake list would swallow.
set(_note "// Generated by FunkGui's cmake/FunkGuiEmbed.cmake (FUNKGUI_WITH_JUCE=OFF): do not edit.")
set(_h "#pragma once\n\n${_note}\n\nnamespace ${FUNKGUI_EMBED_NAMESPACE}\n{\n")
set(_c "${_note}\n\n#include \"${FUNKGUI_EMBED_NAME}.h\"\n\nnamespace\n{\n")
set(_defs "")
set(_group "0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,")
foreach(_entry IN LISTS _files)
  if(NOT _entry MATCHES "^([A-Za-z_][A-Za-z0-9_]*)=(.+)$")
    message(FATAL_ERROR "FunkGuiEmbed.cmake: '${_entry}' is not <symbol>=<file>")
  endif()
  set(_sym "${CMAKE_MATCH_1}")
  set(_file "${CMAKE_MATCH_2}")
  if(NOT EXISTS "${_file}" OR IS_DIRECTORY "${_file}")
    message(FATAL_ERROR "FunkGuiEmbed.cmake: no file ${_file}")
  endif()
  file(SIZE "${_file}" _size)
  if(_size EQUAL 0)
    message(FATAL_ERROR "FunkGuiEmbed.cmake: ${_file} is empty")
  endif()
  file(READ "${_file}" _hex HEX)
  string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")
  string(REGEX REPLACE "(${_group})" "\\1\n    " _bytes "${_bytes}")
  get_filename_component(_name "${_file}" NAME)
  string(APPEND _h "    extern const char* ${_sym};\n    const int          ${_sym}Size = ${_size};    // ${_name}\n\n")
  string(APPEND _c "    // ${_name}\n    const unsigned char ${_sym}_bytes[] = {\n    ${_bytes}\n    };\n\n")
  string(APPEND _defs "const char* ${FUNKGUI_EMBED_NAMESPACE}::${_sym} = "
                      "reinterpret_cast<const char*>(${_sym}_bytes);\n")
endforeach()
string(APPEND _h "}\n")
string(APPEND _c "}\n\n${_defs}")

file(WRITE "${FUNKGUI_EMBED_OUT}/${FUNKGUI_EMBED_NAME}.h" "${_h}")
file(WRITE "${FUNKGUI_EMBED_OUT}/${FUNKGUI_EMBED_NAME}.cpp" "${_c}")
